---
- name: Add GTK-2 Engines Murrine
  apt: pkg=gtk2-engines-murrine state=latest

- name: Checking if arc sourcelist exists
  stat: path=/etc/apt/sources.list.d/arc-theme.list
  register: arc_theme_source

- file: path=/etc/foo.conf state=touch mode="0644"
  when: arc_theme_source.stat.exists == False 

- name: Add source list for arc theme
  command: sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.04/ /' >> /etc/apt/sources.list.d/arc-theme.list"
  when: arc_theme_source.stat.exists == False
# sudo_user: "{{ user }}"

- name: Update
  apt: update_cache=yes

- name: Install arc theme
  apt: pkg=arc-theme state=latest

- name: Setting desktop interface
  command: gsettings set org.gnome.desktop.interface gtk-theme "Arc"
  sudo_user: "{{ user }}"

- name: Setting desktop prefs theme
  command: gsettings set org.gnome.desktop.wm.preferences theme "Arc"
  sudo_user: "{{ user }}"

- name: Enable user themes shell extension
  command: gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com']"
  sudo_user: "{{ user }}"

- name: Set shell theme
  command: gsettings set org.gnome.shell.extensions.user-theme name "Arc"
  sudo_user: "{{ user }}"

- name: Cloning ozon icon theme
  git: repo=https://github.com/ozonos/ozon-icon-theme.git
       dest=/tmp/ozon-icon-theme

- name: Installing icon theme
  command: make install chdir=/tmp/ozon-icon-theme

- name: Setting icon theme
  command: gsettings set org.gnome.desktop.interface icon-theme "Ozon"
  sudo_user: "{{ user }}"



#- name: Restarting gnome shell
#  command: gnome-shell --replace &
