---
#- name: Cheking if sublime is installed
#  file: path=/usr/bin/subl state=file
#  register: sublime_installed

- name: Downloading Dropbox
  get_url: url=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.02.12_amd64.deb dest=/tmp/dropbox.deb
  #when: sublime_installed == 0

- name: Installing Dropbox
  apt: deb=/tmp/dropbox.deb
  #when: sublime_installed == 0

- name: Removing dropbox installation
  file: path=/tmp/dropbox.deb state=absent
  #when: sublime_installed == 0
