---
- name: Checking if sublime is installed
  stat: path=/usr/bin/subl
  register: sublime_installed

- name: Downloading Sublime
  get_url: url=http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3083_amd64.deb dest=/tmp/sublime-text.deb
  when: sublime_installed.stat.exists == False

- name: Installing sublime
  apt: deb=/tmp/sublime-text.deb
  when: sublime_installed.stat.exists == False

- name: Removing sublime installation
  file: path=/tmp/sublime-text.deb state=absent
  when: sublime_installed.stat.exists == False
